# Generated by Django 2.0.6 on 2018-06-20 20:40

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerminationReportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document1', models.FileField(upload_to='documents/')),
                ('document2', models.FileField(upload_to='documents/')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('yaCharField', models.CharField(max_length=10)),
            ],
        ),
    ]
