# Generated by Django 2.0.6 on 2018-06-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termination', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminationreportrequest',
            name='yaCharField',
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
