# Generated by Django 2.0.6 on 2018-06-21 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('termination', '0004_auto_20180620_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 9, 29, 7, 11466, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 9, 29, 7, 11511, tzinfo=utc)),
        ),
    ]
