# Generated by Django 2.0.6 on 2018-06-21 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('termination', '0005_auto_20180621_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 11, 12, 53, 499867, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='document1',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='document2',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 11, 12, 53, 499908, tzinfo=utc)),
        ),
    ]
