# Generated by Django 2.0.6 on 2018-06-21 11:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('termination', '0006_auto_20180621_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminationReportResponse',
            fields=[
                ('requestId', models.UUIDField()),
                ('responseId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report', models.FileField(upload_to='')),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 6, 21, 11, 18, 52, 586480, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 11, 18, 52, 585761, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 11, 18, 52, 585791, tzinfo=utc)),
        ),
    ]
