# Generated by Django 2.0.6 on 2018-06-21 11:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('termination', '0007_auto_20180621_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminationreportresponse',
            old_name='responseId',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='terminationreportresponse',
            name='requestId',
        ),
        migrations.AddField(
            model_name='terminationreportresponse',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 11, 52, 25, 222254, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='terminationreportresponse',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='termination.TerminationReportRequest'),
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 11, 52, 25, 221544, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 11, 52, 25, 221574, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='terminationreportresponse',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 11, 52, 25, 222219, tzinfo=utc), editable=False),
        ),
    ]
