# Generated by Django 2.0.6 on 2018-06-21 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('termination', '0009_auto_20180621_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 12, 20, 7, 841076, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='document1',
            field=models.FileField(upload_to='requests/'),
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='document2',
            field=models.FileField(upload_to='requests/'),
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 12, 20, 7, 841118, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='terminationreportresponse',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 12, 20, 7, 842033, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='terminationreportresponse',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 12, 20, 7, 842067, tzinfo=utc)),
        ),
    ]
