# Generated by Django 2.0.6 on 2018-06-21 14:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('termination', '0011_auto_20180621_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 14, 58, 3, 502991, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 14, 58, 3, 503025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='terminationreportresponse',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 14, 58, 3, 503724, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='terminationreportresponse',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 14, 58, 3, 503750, tzinfo=utc)),
        ),
    ]
