# Generated by Django 2.0.6 on 2018-07-13 21:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('termination', '0012_auto_20180621_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 21, 16, 9, 989161, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 21, 16, 9, 989191, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='terminationreportresponse',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 21, 16, 9, 989632, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='terminationreportresponse',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 21, 16, 9, 989655, tzinfo=utc)),
        ),
    ]
