# Generated by Django 2.0.6 on 2018-07-17 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerminationReportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document1', models.FileField(upload_to='requests/')),
                ('document2', models.FileField(upload_to='requests/')),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 7, 17, 19, 46, 23, 813561, tzinfo=utc), editable=False)),
                ('modified', models.DateTimeField(default=datetime.datetime(2018, 7, 17, 19, 46, 23, 813608, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='TerminationReportResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report', models.FileField(upload_to='responses/')),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 7, 17, 19, 46, 23, 814215, tzinfo=utc), editable=False)),
                ('modified', models.DateTimeField(default=datetime.datetime(2018, 7, 17, 19, 46, 23, 814234, tzinfo=utc))),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webrequest.TerminationReportRequest')),
            ],
        ),
    ]
