# Generated by Django 2.0.6 on 2018-07-17 20:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webrequest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramReportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document1', models.FileField(upload_to='requests/')),
                ('document2', models.FileField(upload_to='requests/')),
                ('document3', models.FileField(upload_to='requests/')),
                ('document4', models.FileField(upload_to='requests/')),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 7, 16, 1380, tzinfo=utc), editable=False)),
                ('modified', models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 7, 16, 1398, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='TelegramReportResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report', models.FileField(upload_to='responses/')),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 7, 16, 1723, tzinfo=utc), editable=False)),
                ('modified', models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 7, 16, 1745, tzinfo=utc))),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webrequest.TelegramReportRequest')),
            ],
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 7, 16, 484, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 7, 16, 513, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='terminationreportresponse',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 7, 16, 974, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='terminationreportresponse',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 7, 16, 993, tzinfo=utc)),
        ),
    ]
