# Generated by Django 2.0.6 on 2018-07-27 04:19

from django.db import migrations

def create_seed_reports(apps, schema_editor):
    Report = apps.get_model('webrequest', 'Report')

    r = Report.objects.create(key="termination",
                                name = "Termination report",
                                description = "Merge termination reports from 1C and Lanteria",
                                maxDocuments = 2)
    r.save()

    r = Report.objects.create(key = "telegram",
                                name = "Telegram report",
                                description = "Check correlation between inten.to, tlgrm.ru, tchannels.me and tsear.ch databases",
                                maxDocuments = 4)
    r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('webrequest', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_seed_reports)
    ]
