# Generated by Django 2.0.6 on 2018-07-17 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webrequest', '0002_auto_20180717_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramreportrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 7, 55, 280944, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='telegramreportrequest',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 7, 55, 280960, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='telegramreportresponse',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 7, 55, 281271, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='telegramreportresponse',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 7, 55, 281293, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 7, 55, 280107, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 7, 55, 280135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='terminationreportresponse',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 7, 55, 280545, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='terminationreportresponse',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 7, 55, 280563, tzinfo=utc)),
        ),
    ]
