# Generated by Django 2.0.6 on 2018-07-17 20:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webrequest', '0003_auto_20180717_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramreportrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 8, 37, 128471, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='telegramreportrequest',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 8, 37, 128489, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='telegramreportresponse',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 8, 37, 128798, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='telegramreportresponse',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 8, 37, 128815, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 8, 37, 127571, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='terminationreportrequest',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 8, 37, 127602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='terminationreportresponse',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 8, 37, 128083, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='terminationreportresponse',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 20, 8, 37, 128100, tzinfo=utc)),
        ),
    ]
